export const BRAZIL_STATES = [
  { value: "AC", label: "Acre", region: "Norte" },
  { value: "AL", label: "Alagoas", region: "Nordeste" },
  { value: "AP", label: "Amapá", region: "Norte" },
  { value: "AM", label: "Amazonas", region: "Norte" },
  { value: "BA", label: "Bahia", region: "Nordeste" },
  { value: "CE", label: "Ceará", region: "Nordeste" },
  { value: "DF", label: "Distrito Federal", region: "Centro-Oeste" },
  { value: "ES", label: "Espírito Santo", region: "Sudeste" },
  { value: "GO", label: "Goiás", region: "Centro-Oeste" },
  { value: "MA", label: "Maranhão", region: "Nordeste" },
  { value: "MT", label: "Mato Grosso", region: "Centro-Oeste" },
  { value: "MS", label: "Mato Grosso do Sul", region: "Centro-Oeste" },
  { value: "MG", label: "Minas Gerais", region: "Sudeste" },
  { value: "PA", label: "Pará", region: "Norte" },
  { value: "PB", label: "Paraíba", region: "Nordeste" },
  { value: "PR", label: "Paraná", region: "Sul" },
  { value: "PE", label: "Pernambuco", region: "Nordeste" },
  { value: "PI", label: "Piauí", region: "Nordeste" },
  { value: "RJ", label: "Rio de Janeiro", region: "Sudeste" },
  { value: "RN", label: "Rio Grande do Norte", region: "Nordeste" },
  { value: "RS", label: "Rio Grande do Sul", region: "Sul" },
  { value: "RO", label: "Rondônia", region: "Norte" },
  { value: "RR", label: "Roraima", region: "Norte" },
  { value: "SC", label: "Santa Catarina", region: "Sul" },
  { value: "SP", label: "São Paulo", region: "Sudeste" },
  { value: "SE", label: "Sergipe", region: "Nordeste" },
  { value: "TO", label: "Tocantins", region: "Norte" },
];

export const REGIONS = ["Norte", "Nordeste", "Centro-Oeste", "Sudeste", "Sul"];
